import localFont from "next/font/local";
import "./globals.css";
import ThirdwebProviderV4 from "@/providers/ThirdwebProviderV4";
import ThirdwebProviderV5 from "@/providers/ThirdwebProviderV5";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThirdwebProviderV4>
          <ThirdwebProviderV5>
            <body>{children}</body>
          </ThirdwebProviderV5>
        </ThirdwebProviderV4>
      </body>
    </html>
  );
}
